# -*- coding: utf-8 -*-
"""modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vnsIBbDfW-8liW1WnLIoiz2hzgMnW46s
"""

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import mlflow
import mlflow.sklearn
from dagshub import dagshub_logger
import dagshub

dagshub.init(repo_owner='ghifari.fikri.yulistia', repo_name='Eksperimen_SML_Ghifari-Fikri-Yulistia', mlflow=True)

mlflow.set_experiment("spam_classifier_experiment")

mlflow.sklearn.autolog()

X = pd.read_csv("spam_ham_emails_preprocessing/tfidf.csv")
y = pd.read_csv("spam_ham_emails_preprocessing/labels.csv")["label"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

with mlflow.start_run():
    print("▶️ Training model...")

    model = LogisticRegression(max_iter=200)
    model.fit(X_train, y_train)

    acc = accuracy_score(y_test, model.predict(X_test))
    print("✅ Done. Akurasi:", acc)

    mlflow.log_metric("custom_accuracy", acc)
    mlflow.log_param("model_type", "LogisticRegression")
